package tui

import (
	"fmt"
	"strings"
	"time"
)

// PromptType defines the target audience for the prompt
type PromptType string

const (
	// PromptTypeChatbot for web-based AI (Grok, ChatGPT, Claude)
	PromptTypeChatbot PromptType = "chatbot"

	// PromptTypeTerminal for terminal AI (Claude Code, Warp, Copilot CLI)
	PromptTypeTerminal PromptType = "terminal"
)

// GenerateTerminalPrompt creates a command-focused prompt for terminal AI tools
func (pg *PromptGenerator) GenerateTerminalPrompt() string {
	var b strings.Builder

	// Terminal AI prompts are concise and command-focused
	b.WriteString("# R8S Terminal AI Analysis\n\n")
	b.WriteString(fmt.Sprintf("Bundle: %s\n", pg.bundlePath))
	
	if pg.bundleHealth != nil {
		b.WriteString(fmt.Sprintf("Health: %d%% | Type: %s\n", 
			pg.bundleHealth.Percentage(), pg.bundleHealth.BundleType))
	}
	
	b.WriteString("\n## Issues Found\n\n")

	// List critical issues with kubectl context
	for i, f := range pg.findings {
		if f.Severity == SeverityCritical {
			b.WriteString(fmt.Sprintf("%d. [%s] %s\n", i+1, f.Title, f.Description))
			if f.Namespace != "" && f.Namespace != "cluster" {
				b.WriteString(fmt.Sprintf("   Namespace: %s\n", f.Namespace))
			}
			if f.PodName != "" {
				b.WriteString(fmt.Sprintf("   Pod: %s\n", f.PodName))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("\n---\n\n")

	// Terminal AI request - focused on commands
	b.WriteString("Generate kubectl commands to diagnose and fix these issues. ")
	b.WriteString("For each issue, provide:\n\n")
	b.WriteString("1. **Diagnostic command** (what to run to investigate)\n")
	b.WriteString("2. **Fix command** (kubectl patch, edit, or delete/recreate)\n")
	b.WriteString("3. **Verify command** (how to confirm the fix worked)\n\n")
	
	b.WriteString("Format as copy-paste ready commands with brief comments. ")
	b.WriteString("Use actual resource names from the context above.\n\n")
	
	b.WriteString("Example format:\n")
	b.WriteString("```bash\n")
	b.WriteString("# Check pod status\n")
	b.WriteString("kubectl get pod <pod-name> -n <namespace> -o yaml\n\n")
	b.WriteString("# Fix: Increase memory limit\n")
	b.WriteString("kubectl patch deployment <name> -n <namespace> -p '{\"spec\":{...}}'\n\n")
	b.WriteString("# Verify\n")
	b.WriteString("kubectl get pods -n <namespace> | grep <pod-name>\n")
	b.WriteString("```\n")

	return b.String()
}

// GenerateFixScriptPrompt creates a shell script generation prompt
func (pg *PromptGenerator) GenerateFixScriptPrompt() string {
	var b strings.Builder

	b.WriteString("#!/bin/bash\n")
	b.WriteString("# R8S Auto-Remediation Script Generator\n")
	b.WriteString(fmt.Sprintf("# Bundle: %s\n", pg.bundlePath))
	b.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString("#\n")
	b.WriteString("# This script was generated by r8s to fix detected issues.\n")
	b.WriteString("# Review before running in production.\n\n")

	b.WriteString("set -euo pipefail\n\n")
	b.WriteString(fmt.Sprintf("NAMESPACE=\"%s\"\n", pg.getPrimaryNamespace()))
	b.WriteString(fmt.Sprintf("BUNDLE_PATH=\"%s\"\n\n", pg.bundlePath))

	b.WriteString("echo \"=== R8S Remediation Script ===\"\n")
	b.WriteString("echo \"Bundle: $BUNDLE_PATH\"\n")
	b.WriteString("echo \"\"\n\n")

	// Add context about issues
	b.WriteString("# Issues detected:\n")
	for _, f := range pg.findings {
		if f.Severity == SeverityCritical {
			b.WriteString(fmt.Sprintf("# - %s: %s\n", f.Title, f.Description))
		}
	}
	b.WriteString("\n")

	b.WriteString("---\n\n")

	b.WriteString("Generate a bash script that:\n")
	b.WriteString("1. Checks each issue with kubectl diagnostics\n")
	b.WriteString("2. Applies safe fixes (with user confirmation prompts)\n")
	b.WriteString("3. Verifies fixes with health checks\n")
	b.WriteString("4. Outputs clear status messages\n\n")
	
	b.WriteString("Requirements:\n")
	b.WriteString("- Use variables for namespace/pod names from context above\n")
	b.WriteString("- Add 'read -p' prompts before destructive operations\n")
	b.WriteString("- Include error handling and rollback options\n")
	b.WriteString("- Make it idempotent (safe to run multiple times)\n")
	b.WriteString("- End with verification that issues are resolved\n")

	return b.String()
}

// getPrimaryNamespace returns the most common namespace from findings
func (pg *PromptGenerator) getPrimaryNamespace() string {
	namespaceCount := make(map[string]int)
	for _, f := range pg.findings {
		if f.Namespace != "" && f.Namespace != "cluster" {
			namespaceCount[f.Namespace]++
		}
	}

	maxCount := 0
	primaryNs := "default"
	for ns, count := range namespaceCount {
		if count > maxCount {
			maxCount = count
			primaryNs = ns
		}
	}

	return primaryNs
}

// GetPromptForType returns the appropriate prompt for the given type
func (pg *PromptGenerator) GetPromptForType(promptType PromptType) string {
	switch promptType {
	case PromptTypeTerminal:
		return pg.GenerateTerminalPrompt()
	default:
		return pg.GenerateSupportPrompt()
	}
}

// GetPromptTypeDescription returns a description of each prompt type
func GetPromptTypeDescription(t PromptType) string {
	switch t {
	case PromptTypeTerminal:
		return "Terminal AI (Claude Code, Warp) - Command-focused, kubectl scripts"
	default:
		return "Chatbot (Grok, ChatGPT) - Analysis and explanation-focused"
	}
}

// ListAvailablePromptTypes returns all available prompt types
func ListAvailablePromptTypes() []PromptType {
	return []PromptType{PromptTypeChatbot, PromptTypeTerminal}
}
