apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
  uid: bdf3c31f691dd59f2f90f54ef9e26ed0
spec:
  containers:
  - args:
    - --permit-port-sharing=true
    - --authentication-kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    - --authorization-kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    - --bind-address=127.0.0.1
    - --cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler
    - --kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    - --profiling=false
    - --secure-port=10259
    - --tls-cert-file=/var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
    - --tls-private-key-file=/var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key
    command:
    - kube-scheduler
    env:
    - name: FILE_HASH
      value: 83c9e80bd05d3b549d91aaa42d69bc7b25d5bf7c3768ed653626b72a7f19191f
    - name: NO_PROXY
      value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    image: index.docker.io/rancher/hardened-kubernetes:v1.33.7-rke2r1-build20251210
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /livez
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    ports:
    - containerPort: 10259
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: localhost
        path: /readyz
        port: 10259
        scheme: HTTPS
      periodSeconds: 1
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      privileged: false
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: localhost
        path: /livez
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/rancher/rke2/server/db/etcd/name
      name: file0
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
      name: file1
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/client-scheduler.crt
      name: file2
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/client-scheduler.key
      name: file3
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
      name: file4
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key
      name: file5
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/server-ca.crt
      name: file6
      readOnly: true
    - mountPath: /var/lib/rancher/rke2/server/tls/kube-scheduler
      name: extra-mount-0
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/rancher/rke2/server/db/etcd/name
      type: File
    name: file0
  - hostPath:
      path: /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
      type: File
    name: file1
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/client-scheduler.crt
      type: File
    name: file2
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/client-scheduler.key
      type: File
    name: file3
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
      type: File
    name: file4
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key
      type: File
    name: file5
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/server-ca.crt
      type: File
    name: file6
  - hostPath:
      path: /var/lib/rancher/rke2/server/tls/kube-scheduler
      type: Directory
    name: extra-mount-0
status: {}
